
Try/catch system
	void f() throw an "error";

	try {
		f()
	}
	catch an error print( error );

	@?
		block (0) {
			const "an"
			const "error"
			body:
				throw 1 2
		}
		const "an"
		body:
			voidcall 1 0
			jumperr 1
			return 0
			geterr 3 4
			eq 2 3 5
			jumpif 5 1
			throw 3 4
			load #std:print 3
			voidcall 3 1
	?@

Try syntax improvement
	try f;
	catch an error print( error );

Grrr my amazing class<interface> idea won't work :/
